<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: api/users/v1/service.proto

namespace Spiral\Shared\Services\Users\v1;

use Spiral\RoadRunner\GRPC;

interface UsersServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "api.users.v1.UsersService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Users\v1\DTO\AuthRequest $in
    * @return \Spiral\Shared\Services\Users\v1\DTO\AuthResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Auth(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Users\v1\DTO\AuthRequest $in): \Spiral\Shared\Services\Users\v1\DTO\AuthResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Users\v1\DTO\RegisterRequest $in
    * @return \Spiral\Shared\Services\Users\v1\DTO\RegisterResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Register(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Users\v1\DTO\RegisterRequest $in): \Spiral\Shared\Services\Users\v1\DTO\RegisterResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Users\v1\DTO\GetRequest $in
    * @return \Spiral\Shared\Services\Users\v1\DTO\GetResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Get(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Users\v1\DTO\GetRequest $in): \Spiral\Shared\Services\Users\v1\DTO\GetResponse;
}
