version: '2.7'

rpc:
    listen: tcp://0.0.0.0:6001

server:
    command: "php app.php"
    relay: pipes

logs:
    level: info

jobs:
    consume: [ ]
    pool:
        num_workers: 2
        supervisor:
            max_worker_memory: 100

grpc:
    listen: "tcp://0.0.0.0:9000"
    pool:
        num_workers: 5
    proto:
        - "./proto/api/payment/v1/service.proto"
