<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: api/cinema/v1/service.proto

namespace Spiral\Shared\Services\Cinema\v1;

use Spiral\RoadRunner\GRPC;

interface CinemaServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "api.cinema.v1.CinemaService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\ScheduleRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\ScheduleResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Schedule(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\ScheduleRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\ScheduleResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Screening(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\CheckSeatsRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\CheckSeatsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CheckSeats(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\CheckSeatsRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\CheckSeatsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\ReserveRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\ReserveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Reserve(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\ReserveRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\ReserveResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\ReservationsRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\ReservationsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Reservations(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\ReservationsRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\ReservationsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\CancelRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\CancelResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Cancel(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\CancelRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\CancelResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Cinema\v1\DTO\PurchaseRequest $in
    * @return \Spiral\Shared\Services\Cinema\v1\DTO\PurchaseResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Purchase(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Cinema\v1\DTO\PurchaseRequest $in): \Spiral\Shared\Services\Cinema\v1\DTO\PurchaseResponse;
}
