<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/payment/v1/message.proto

namespace Spiral\Shared\Services\Payment\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.payment.v1.dto.Payment</code>
 */
class Payment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string email = 2;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money money = 3;</code>
     */
    protected $money = null;
    /**
     * Generated from protobuf field <code>string payment_method = 4;</code>
     */
    protected $payment_method = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type string $email
     *     @type \Spiral\Shared\Services\Common\v1\DTO\Money $money
     *     @type string $payment_method
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Payment\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money money = 3;</code>
     * @return \Spiral\Shared\Services\Common\v1\DTO\Money
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money money = 3;</code>
     * @param \Spiral\Shared\Services\Common\v1\DTO\Money $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Common\v1\DTO\Money::class);
        $this->money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_method = 4;</code>
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->payment_method;
    }

    /**
     * Generated from protobuf field <code>string payment_method = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_method = $var;

        return $this;
    }

}

