<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/payment/v1/message.proto

namespace Spiral\Shared\Services\Payment\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.payment.v1.dto.Receipt</code>
 */
class Receipt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string transaction_id = 2;</code>
     */
    protected $transaction_id = '';
    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money money = 4;</code>
     */
    protected $money = null;
    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money fee = 5;</code>
     */
    protected $fee = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     */
    protected $created_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $transaction_id
     *     @type \Spiral\Shared\Services\Common\v1\DTO\Money $money
     *     @type \Spiral\Shared\Services\Common\v1\DTO\Money $fee
     *     @type \Google\Protobuf\Timestamp $created_at
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Payment\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 2;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money money = 4;</code>
     * @return \Spiral\Shared\Services\Common\v1\DTO\Money
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money money = 4;</code>
     * @param \Spiral\Shared\Services\Common\v1\DTO\Money $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Common\v1\DTO\Money::class);
        $this->money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money fee = 5;</code>
     * @return \Spiral\Shared\Services\Common\v1\DTO\Money
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money fee = 5;</code>
     * @param \Spiral\Shared\Services\Common\v1\DTO\Money $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Common\v1\DTO\Money::class);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

}

