{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Registered users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Current reservations",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reservations", "legendFormat": "Reservations" }
   ]
  },
  {
   "title": "Total payments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_transactions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Money earned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "money_sum", "legendFormat": "$" }
   ]
  },
  {
   "title": "Fees earned [$]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "money_fee_sum / 100", "legendFormat": "$" }
   ]
  },
  {
   "title": "Tickets by movie",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(movie) (tickets_reservation)",
     "legendFormat": "{{movie}}"
    }
   ]
  },
  {
   "title": "Tickets by auditorium",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(auditorium) (tickets_reservation)",
     "legendFormat": "{{auditorium}}"
    }
   ]
  },
  {
   "title": "Tickets by price",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(price) (tickets_reservation)",
     "legendFormat": "{{price}}$"
    }
   ]
  }
 ]
}