<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cinema/v1/message.proto

namespace Spiral\Shared\Services\Cinema\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.cinema.v1.dto.CancelRequest</code>
 */
class CancelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string reservation_id = 1;</code>
     */
    protected $reservation_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reservation_id
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Cinema\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string reservation_id = 1;</code>
     * @return string
     */
    public function getReservationId()
    {
        return $this->reservation_id;
    }

    /**
     * Generated from protobuf field <code>string reservation_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReservationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->reservation_id = $var;

        return $this;
    }

}

