<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cinema/v1/message.proto

namespace Spiral\Shared\Services\Cinema\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.cinema.v1.dto.ReserveResponse</code>
 */
class ReserveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Reservation reservation = 1;</code>
     */
    protected $reservation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\Reservation $reservation
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Cinema\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Reservation reservation = 1;</code>
     * @return \Spiral\Shared\Services\Cinema\v1\DTO\Reservation
     */
    public function getReservation()
    {
        return $this->reservation;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Reservation reservation = 1;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\Reservation $var
     * @return $this
     */
    public function setReservation($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Cinema\v1\DTO\Reservation::class);
        $this->reservation = $var;

        return $this;
    }

}

