<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cinema/v1/message.proto

namespace Spiral\Shared\Services\Cinema\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.cinema.v1.dto.Reservation</code>
 */
class Reservation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>repeated .api.cinema.v1.dto.Seat seats = 2;</code>
     */
    private $seats;
    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Screening screening = 3;</code>
     */
    protected $screening = null;
    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money total_cost = 4;</code>
     */
    protected $total_cost = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp canceled_at = 6;</code>
     */
    protected $canceled_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expires_at = 7;</code>
     */
    protected $expires_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp paid_at = 8;</code>
     */
    protected $paid_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\Seat[]|\Google\Protobuf\Internal\RepeatedField $seats
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\Screening $screening
     *     @type \Spiral\Shared\Services\Common\v1\DTO\Money $total_cost
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $canceled_at
     *     @type \Google\Protobuf\Timestamp $expires_at
     *     @type \Google\Protobuf\Timestamp $paid_at
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Cinema\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .api.cinema.v1.dto.Seat seats = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSeats()
    {
        return $this->seats;
    }

    /**
     * Generated from protobuf field <code>repeated .api.cinema.v1.dto.Seat seats = 2;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\Seat[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSeats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Spiral\Shared\Services\Cinema\v1\DTO\Seat::class);
        $this->seats = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Screening screening = 3;</code>
     * @return \Spiral\Shared\Services\Cinema\v1\DTO\Screening
     */
    public function getScreening()
    {
        return $this->screening;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Screening screening = 3;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\Screening $var
     * @return $this
     */
    public function setScreening($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Cinema\v1\DTO\Screening::class);
        $this->screening = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money total_cost = 4;</code>
     * @return \Spiral\Shared\Services\Common\v1\DTO\Money
     */
    public function getTotalCost()
    {
        return $this->total_cost;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money total_cost = 4;</code>
     * @param \Spiral\Shared\Services\Common\v1\DTO\Money $var
     * @return $this
     */
    public function setTotalCost($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Common\v1\DTO\Money::class);
        $this->total_cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp canceled_at = 6;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCanceledAt()
    {
        return $this->canceled_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp canceled_at = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCanceledAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->canceled_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expires_at = 7;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expires_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->expires_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp paid_at = 8;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getPaidAt()
    {
        return $this->paid_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp paid_at = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setPaidAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->paid_at = $var;

        return $this;
    }

}

