<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cinema/v1/message.proto

namespace Spiral\Shared\Services\Cinema\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.cinema.v1.dto.ScreeningFull</code>
 */
class ScreeningFull extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Movie movie = 2;</code>
     */
    protected $movie = null;
    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Auditorium auditorium = 3;</code>
     */
    protected $auditorium = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp starts_at = 4;</code>
     */
    protected $starts_at = null;
    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money price = 5;</code>
     */
    protected $price = null;
    /**
     * Generated from protobuf field <code>repeated .api.cinema.v1.dto.Seat reserved_seats = 7;</code>
     */
    private $reserved_seats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\Movie $movie
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\Auditorium $auditorium
     *     @type \Google\Protobuf\Timestamp $starts_at
     *     @type \Spiral\Shared\Services\Common\v1\DTO\Money $price
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\Seat[]|\Google\Protobuf\Internal\RepeatedField $reserved_seats
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Cinema\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Movie movie = 2;</code>
     * @return \Spiral\Shared\Services\Cinema\v1\DTO\Movie
     */
    public function getMovie()
    {
        return $this->movie;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Movie movie = 2;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\Movie $var
     * @return $this
     */
    public function setMovie($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Cinema\v1\DTO\Movie::class);
        $this->movie = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Auditorium auditorium = 3;</code>
     * @return \Spiral\Shared\Services\Cinema\v1\DTO\Auditorium
     */
    public function getAuditorium()
    {
        return $this->auditorium;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.Auditorium auditorium = 3;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\Auditorium $var
     * @return $this
     */
    public function setAuditorium($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Cinema\v1\DTO\Auditorium::class);
        $this->auditorium = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp starts_at = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getStartsAt()
    {
        return $this->starts_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp starts_at = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartsAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->starts_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money price = 5;</code>
     * @return \Spiral\Shared\Services\Common\v1\DTO\Money
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>.api.common.v1.dto.Money price = 5;</code>
     * @param \Spiral\Shared\Services\Common\v1\DTO\Money $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Common\v1\DTO\Money::class);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .api.cinema.v1.dto.Seat reserved_seats = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReservedSeats()
    {
        return $this->reserved_seats;
    }

    /**
     * Generated from protobuf field <code>repeated .api.cinema.v1.dto.Seat reserved_seats = 7;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\Seat[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReservedSeats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Spiral\Shared\Services\Cinema\v1\DTO\Seat::class);
        $this->reserved_seats = $arr;

        return $this;
    }

}

