<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cinema/v1/message.proto

namespace Spiral\Shared\Services\Cinema\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.cinema.v1.dto.ScreeningResponse</code>
 */
class ScreeningResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.ScreeningFull screening = 1;</code>
     */
    protected $screening = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningFull $screening
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Cinema\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.ScreeningFull screening = 1;</code>
     * @return \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningFull
     */
    public function getScreening()
    {
        return $this->screening;
    }

    /**
     * Generated from protobuf field <code>.api.cinema.v1.dto.ScreeningFull screening = 1;</code>
     * @param \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningFull $var
     * @return $this
     */
    public function setScreening($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Cinema\v1\DTO\ScreeningFull::class);
        $this->screening = $var;

        return $this;
    }

}

