<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: api/payment/v1/service.proto

namespace Spiral\Shared\Services\Payment\v1;

use Spiral\RoadRunner\GRPC;

interface PaymentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "api.payment.v1.PaymentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Payment\v1\DTO\ChargeRequest $in
    * @return \Spiral\Shared\Services\Payment\v1\DTO\ChargeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Charge(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Payment\v1\DTO\ChargeRequest $in): \Spiral\Shared\Services\Payment\v1\DTO\ChargeResponse;
}
