<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/centrifugo/v1/message.proto

namespace Spiral\Shared\Services\Centrifugo\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.centrifugo.v1.dto.ChannelsResult</code>
 */
class ChannelsResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .api.centrifugo.v1.dto.ChannelInfo> channels = 1;</code>
     */
    private $channels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $channels
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Centrifugo\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .api.centrifugo.v1.dto.ChannelInfo> channels = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * Generated from protobuf field <code>map<string, .api.centrifugo.v1.dto.ChannelInfo> channels = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setChannels($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Spiral\Shared\Services\Centrifugo\v1\DTO\ChannelInfo::class);
        $this->channels = $arr;

        return $this;
    }

}

