<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/centrifugo/v1/message.proto

namespace Spiral\Shared\Services\Centrifugo\v1\DTO;

if (false) {
    /**
     * This class is deprecated. Use Spiral\Shared\Services\Centrifugo\v1\DTO\Command\MethodType instead.
     * @deprecated
     */
    class Command_MethodType {}
}
class_exists(Command\MethodType::class);
@trigger_error('Spiral\Shared\Services\Centrifugo\v1\DTO\Command_MethodType is deprecated and will be removed in the next major release. Use Spiral\Shared\Services\Centrifugo\v1\DTO\Command\MethodType instead', E_USER_DEPRECATED);

