<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/centrifugo/v1/message.proto

namespace Spiral\Shared\Services\Centrifugo\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.centrifugo.v1.dto.DisconnectRequest</code>
 */
class DisconnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user = 1;</code>
     */
    protected $user = '';
    /**
     * Generated from protobuf field <code>.api.centrifugo.v1.dto.Disconnect disconnect = 2;</code>
     */
    protected $disconnect = null;
    /**
     * Generated from protobuf field <code>string client = 3;</code>
     */
    protected $client = '';
    /**
     * Generated from protobuf field <code>repeated string whitelist = 4;</code>
     */
    private $whitelist;
    /**
     * Generated from protobuf field <code>string session = 5;</code>
     */
    protected $session = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user
     *     @type \Spiral\Shared\Services\Centrifugo\v1\DTO\Disconnect $disconnect
     *     @type string $client
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $whitelist
     *     @type string $session
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Centrifugo\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user = 1;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.centrifugo.v1.dto.Disconnect disconnect = 2;</code>
     * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\Disconnect
     */
    public function getDisconnect()
    {
        return $this->disconnect;
    }

    /**
     * Generated from protobuf field <code>.api.centrifugo.v1.dto.Disconnect disconnect = 2;</code>
     * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\Disconnect $var
     * @return $this
     */
    public function setDisconnect($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Centrifugo\v1\DTO\Disconnect::class);
        $this->disconnect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client = 3;</code>
     * @return string
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>string client = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkString($var, True);
        $this->client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string whitelist = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWhitelist()
    {
        return $this->whitelist;
    }

    /**
     * Generated from protobuf field <code>repeated string whitelist = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWhitelist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->whitelist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session = 5;</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Generated from protobuf field <code>string session = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->session = $var;

        return $this;
    }

}

