<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/centrifugo/v1/message.proto

namespace Spiral\Shared\Services\Centrifugo\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.centrifugo.v1.dto.HistoryRequest</code>
 */
class HistoryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>int32 limit = 2;</code>
     */
    protected $limit = 0;
    /**
     * Generated from protobuf field <code>.api.centrifugo.v1.dto.StreamPosition since = 3;</code>
     */
    protected $since = null;
    /**
     * Generated from protobuf field <code>bool reverse = 4;</code>
     */
    protected $reverse = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $channel
     *     @type int $limit
     *     @type \Spiral\Shared\Services\Centrifugo\v1\DTO\StreamPosition $since
     *     @type bool $reverse
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Centrifugo\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.centrifugo.v1.dto.StreamPosition since = 3;</code>
     * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\StreamPosition
     */
    public function getSince()
    {
        return $this->since;
    }

    /**
     * Generated from protobuf field <code>.api.centrifugo.v1.dto.StreamPosition since = 3;</code>
     * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\StreamPosition $var
     * @return $this
     */
    public function setSince($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Centrifugo\v1\DTO\StreamPosition::class);
        $this->since = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reverse = 4;</code>
     * @return bool
     */
    public function getReverse()
    {
        return $this->reverse;
    }

    /**
     * Generated from protobuf field <code>bool reverse = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setReverse($var)
    {
        GPBUtil::checkBool($var);
        $this->reverse = $var;

        return $this;
    }

}

