<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/centrifugo/v1/message.proto

namespace Spiral\Shared\Services\Centrifugo\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.centrifugo.v1.dto.Process</code>
 */
class Process extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double cpu = 1;</code>
     */
    protected $cpu = 0.0;
    /**
     * Generated from protobuf field <code>int64 rss = 2;</code>
     */
    protected $rss = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $cpu
     *     @type int|string $rss
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Centrifugo\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double cpu = 1;</code>
     * @return float
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    /**
     * Generated from protobuf field <code>double cpu = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkDouble($var);
        $this->cpu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rss = 2;</code>
     * @return int|string
     */
    public function getRss()
    {
        return $this->rss;
    }

    /**
     * Generated from protobuf field <code>int64 rss = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRss($var)
    {
        GPBUtil::checkInt64($var);
        $this->rss = $var;

        return $this;
    }

}

