<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/users/v1/message.proto

namespace Spiral\Shared\Services\Users\v1\DTO;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.users.v1.dto.GetResponse</code>
 */
class GetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.api.users.v1.dto.User user = 1;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Spiral\Shared\Services\Users\v1\DTO\User $user
     * }
     */
    public function __construct($data = NULL) {
        \Spiral\Shared\Services\Users\v1\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.api.users.v1.dto.User user = 1;</code>
     * @return \Spiral\Shared\Services\Users\v1\DTO\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.api.users.v1.dto.User user = 1;</code>
     * @param \Spiral\Shared\Services\Users\v1\DTO\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Spiral\Shared\Services\Users\v1\DTO\User::class);
        $this->user = $var;

        return $this;
    }

}

