<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: api/centrifugo/v1/service.proto

namespace Spiral\Shared\Services\Centrifugo\v1;

use Spiral\RoadRunner\GRPC;

interface CentrifugoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "api.centrifugo.v1.CentrifugoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\PublishRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\PublishResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Publish(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\PublishRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\PublishResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\BroadcastRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\BroadcastResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Broadcast(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\BroadcastRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\BroadcastResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\SubscribeRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\SubscribeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Subscribe(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\SubscribeRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\SubscribeResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\UnsubscribeRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\UnsubscribeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Unsubscribe(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\UnsubscribeRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\UnsubscribeResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\DisconnectRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\DisconnectResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Disconnect(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\DisconnectRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\DisconnectResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Presence(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceStatsRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceStatsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function PresenceStats(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceStatsRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\PresenceStatsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function History(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryRemoveRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryRemoveResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function HistoryRemove(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryRemoveRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\HistoryRemoveResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\InfoRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\InfoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Info(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\InfoRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\InfoResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\RPCRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\RPCResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RPC(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\RPCRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\RPCResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\RefreshRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\RefreshResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Refresh(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\RefreshRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\RefreshResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\ChannelsRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\ChannelsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Channels(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\ChannelsRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\ChannelsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\ConnectionsRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\ConnectionsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Connections(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\ConnectionsRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\ConnectionsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\UpdateUserStatusRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\UpdateUserStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UpdateUserStatus(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\UpdateUserStatusRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\UpdateUserStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\GetUserStatusRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\GetUserStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetUserStatus(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\GetUserStatusRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\GetUserStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\DeleteUserStatusRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\DeleteUserStatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DeleteUserStatus(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\DeleteUserStatusRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\DeleteUserStatusResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\BlockUserRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\BlockUserResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function BlockUser(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\BlockUserRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\BlockUserResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\UnblockUserRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\UnblockUserResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UnblockUser(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\UnblockUserRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\UnblockUserResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\RevokeTokenRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\RevokeTokenResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function RevokeToken(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\RevokeTokenRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\RevokeTokenResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Centrifugo\v1\DTO\InvalidateUserTokensRequest $in
    * @return \Spiral\Shared\Services\Centrifugo\v1\DTO\InvalidateUserTokensResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function InvalidateUserTokens(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Centrifugo\v1\DTO\InvalidateUserTokensRequest $in): \Spiral\Shared\Services\Centrifugo\v1\DTO\InvalidateUserTokensResponse;
}
