<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: api/tokens/v1/service.proto

namespace Spiral\Shared\Services\Tokens\v1;

use Spiral\RoadRunner\GRPC;

interface TokensServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "api.tokens.v1.TokensService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Tokens\v1\DTO\CreateRequest $in
    * @return \Spiral\Shared\Services\Tokens\v1\DTO\CreateResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Create(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Tokens\v1\DTO\CreateRequest $in): \Spiral\Shared\Services\Tokens\v1\DTO\CreateResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Tokens\v1\DTO\LoadRequest $in
    * @return \Spiral\Shared\Services\Tokens\v1\DTO\LoadResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Load(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Tokens\v1\DTO\LoadRequest $in): \Spiral\Shared\Services\Tokens\v1\DTO\LoadResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Spiral\Shared\Services\Tokens\v1\DTO\DeleteRequest $in
    * @return \Spiral\Shared\Services\Tokens\v1\DTO\DeleteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Delete(GRPC\ContextInterface $ctx, \Spiral\Shared\Services\Tokens\v1\DTO\DeleteRequest $in): \Spiral\Shared\Services\Tokens\v1\DTO\DeleteResponse;
}
