version: '2.7'

rpc:
    listen: tcp://0.0.0.0:6001

server:
    command: "php app.php"
    relay: pipes

logs:
    level: info

temporal:
    address: temporal:7233
    activities:
        num_workers: 5

grpc:
    listen: "tcp://0.0.0.0:9000"
    pool:
        num_workers: 5
    proto:
        - "./proto/api/users/v1/service.proto"
        - "./proto/api/tokens/v1/service.proto"

broadcast:
    default:
        driver: redis
        config:
            addrs:
                - redis:6379
